resources:
  - name: docker-in-concourse
    type: git
    source:
      uri: https://github.com/xinzweb/docker-in-concourse.git
  - name: docker
    type: docker-image
    source:
      repository: docker
      tag: dind

jobs:
  - name: docker in concourse
    plan:
    - get: docker-in-concourse
    - get: docker
    - task: run dockerd
      image: docker
      privileged: true # required
      config:
        platform: linux
        inputs:
        - name: docker-in-concourse # required
        - name: docker
        run:
          path: sh
          args:
            - -ec
            - |
              ####
              # bash is required to run the dind.bash
              ####
              apk -q update
              apk -q --no-progress add bash
              ####
              # load script
              ####
              . docker-in-concourse/dind.bash
              ####
              # start dockerd
              ####
              export max_concurrent_downloads=4
              export max_concurrent_uploads=4
              start_docker ${max_concurrent_downloads} ${max_concurrent_uploads}
              ####
              # verify the docker works
              ####
              docker images
              docker run -it --rm docker:latest ls
              docker images
